main: com.yahoo.baeshra.EasyInspect.App
name: EasyInspect
version: 0.1
api-version: 1.16
depend: [CoreProtect]
commands:
   ei:
      description: Uses easy inspect
      usage: "/ei <optional: time|m,h,d>"
      permission: easyinspect.inspect 